phrase:
  access_token: beb8d4b2ca41c5079f9f0cd14133980e28627f80ea456ec78ad19d755e8053ab
  project_id: 273addfabbe1e5014e918c00fda8c000
  push:
    sources:
    - file: ./locales/en.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./locales/en.json
      params:
        file_format: simple_json
