import { createStore } from 'vuex';
import { shallowRef } from 'vue';
import { Check, Minus, Warning } from '@element-plus/icons';
import actions from './actions';
import getters from './getters';
import mutations from './mutations';

export default createStore({
  namespaced: true,
  state() {
    return {
      data: {},
      payOnDelivery: {},
      mobile: false,
      dialogVisible: false,
      detailsDialogVisible: false,
      loading: false,
      timelineVisible: true,
      recipientVisible: true,
      ratingVisible: true,
      datePickerVisible: false,
      checkoutDialogVisible: false,
      reviewDialogVisible: false,
      deliveryStatus: 0,
      updateDelivery: null,
      rateOrder: null,
      paymentSuccessful: false,
      checkoutModal: '',
      language: 'en',
      countryData: {
        countryCode: 'KE',
      },
      orderStatuses: [
        'event.delivery.order.created',
        'event.delivery.at.hub.processing.for.delivery',
        'event.delivery.at.hub.partner.assigned',
        'event.delivery.at.hub.waiting.for.partner',
        'event.delivery.partner.enroute.to.hub',
        'event.delivery.partner.arrived.at.hub',
        'event.delivery.partner.pickup.from.hub.confirmed.via.code',
        'event.delivery.partner.enroute.to.buyer.location',
        'event.delivery.partner.arrived.at.buyer.location',
        'event.delivery.partner.submitted.items.to.buyer.confirmed.via.code',
        'event.delivery.order.canceled.by.seller',
        'event.delivery.order.canceled.by.sendy',
        'event.delivery.failed',
        'event.delivery.rescheduled.by.buyer',
        'event.delivery.rescheduled.by.seller',
        'event.delivery.rescheduled.by.sendy',
        // 'event.delivery.buyer.paid.for.goods',
      ],
      orderEvents: [
        'timeline.orderCreated',
        'timeline.orderProcessed',
        'timeline.partnerAssigned',
        'timeline.partnerCollection',
        'timeline.partnerPickup',
        'timeline.partnerArrived',
        'timeline.packageCollected',
        'timeline.packageInTransit',
        'timeline.packageArrived',
        'timeline.deliveryComplete',
        'timeline.orderCancelled',
        'timeline.orderFailed',
        'timeline.partnerIsHere',
        'timeline.partnerAtDestination',
        'timeline.deliveryAttempted',
        'timeline.delay',
        'timeline.orderCancelledDate',
        'timeline.arriving',
        'timeline.deliveryCompleted',
        'timeline.deliveryCompletedDate',
        'timeline.preparingDelivery',
        'timeline.preparedDelivery',
        'timeline.arrivingSoon',
        'timeline.rescheduledByBuyer',
        'timeline.rescheduledBySeller',
        'timeline.rescheduledBySendy',
        'timeline.attemptFailed',
        'timeline.attemptFail',
        'timeline.orderPlaced',
        //
      ],
      orderTimelines: [
        {
          event: 'event.delivery.order.created',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#324ba8', '', ''],
          icons: shallowRef([Check, Minus, '', '']),
          iconClass: ['', 'el-icon-minus', '', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 20, 7, 8],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.at.hub.processing.for.delivery',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#324ba8', '', ''],
          icons: shallowRef([Check, Minus, '', '']),
          iconClass: ['', 'el-icon-minus', '', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 20, 7, 8],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.at.hub.partner.assigned',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Check, Minus, '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'today',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.at.hub.waiting.for.partner',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Check, Minus, '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'today',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.partner.enroute.to.hub',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Check, Minus, '']),
          iconClass: ['', 'el-icon-minus', '', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'today',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.partner.arrived.at.hub',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Check, Minus, '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'today',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.partner.pickup.from.hub.confirmed.via.code',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Check, Minus, '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'today',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 21, 7, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.partner.enroute.to.buyer.location',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Check, Minus, '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, true, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'today',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 21, 22, 17],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.partner.arrived.at.buyer.location',
          steps: [0, 1, 8, 9],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Check, Minus, '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, true, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'today',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 21, 12, 18],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.partner.submitted.items.to.buyer.confirmed.via.code',
          steps: [0, 1, 7, 9],
          colors: ['#EE7D00', '#EE7D00', '#EE7D00', '#EE7D00'],
          icons: shallowRef([Check, Check, Check, Check]),
          iconClass: ['', '', '', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'completed',
              status: true,
              format: 'ddd, MMM Do',
            },
          ],
          titles: [28, 21, 13, 19],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.order.canceled.by.seller',
          steps: [0, 10],
          colors: ['#EE7D00', '#EE7D00'],
          icons: shallowRef([Check, Check]),
          iconClass: ['', ''],
          showDriver: [false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.order.canceled.by.sendy',
          steps: [0, 11],
          colors: ['#EE7D00', '#EE7D00'],
          icons: shallowRef([Check, Check]),
          iconClass: ['', ''],
          showDriver: [false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.failed',
          steps: [0, 1, 7, 12, 9],
          colors: ['#EE7D00', '#EE7D00', '#EE7D00', '#9B101C', '#909399'],
          icons: shallowRef([Check, Check, Check, 'el-icon-remove', '']),
          iconClass: ['', '', '', ''],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
          ],
          titles: [28, 21, 8, 26, 18],
          showReschedule: [false, false, false, true, false],
        },
        {
          event: 'event.delivery.rescheduled.by.buyer',
          steps: [0, 13, 1, 7, 9],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', '', ''],
          icons: shallowRef([Check, Check, Minus, '', '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            { status: false },
          ],
          titles: [28, 23, 1, 7, 18],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.rescheduled.by.seller',
          steps: [0, 14, 1, 7, 9],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', '', ''],
          icons: shallowRef([Check, Check, Minus, '', '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            { status: false },
          ],
          titles: [28, 24, 1, 7, 18],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.rescheduled.by.sendy',
          steps: [0, 15, 1, 7, 9],
          colors: ['#EE7D00', '#EE7D00', '#324ba8', '', ''],
          icons: shallowRef([Check, Check, Minus, '', '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            { status: false },
          ],
          titles: [28, 25, 1, 7, 18],
          showReschedule: [false, false, false, false, false],
        },
        // {
        //   event: 'event.delivery.buyer.paid.for.goods',
        //   steps: [0, 1, 8, 9],
        //   colors: ['#EE7D00', '#EE7D00', '#324ba8', ''],
        //   icons: shallowRef([Check, Check, Minus, '']),
        //   iconClass: ['', '', 'el-icon-minus', ''],
        //   showDriver: [false, false, true, false],
        //   dates: [
        //     {
        //       type: 'timeline',
        //       status: true,
        //       format: 'ddd, MMM Do',
        //     },
        //     { status: false },
        //     { status: false },
        //     {
        //       type: 'today',
        //       status: true,
        //       format: 'dddd',
        //     },
        //   ],
        //   titles: [28, 21, 12, 18],
        //   showReschedule: [false, false, false, false],
        // },
      ],
      rescheduledOrderTimelines: [
        {
          event: 'event.delivery.order.created',
          steps: [0, 1, 7, 8],
          colors: ['#EE7D00', '#324ba8', '', ''],
          icons: shallowRef([Check, Minus, '', '']),
          iconClass: ['', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'dddd',
            },
          ],
          titles: [28, 20, 7, 8],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.at.hub.processing.for.delivery',
          steps: [0, 12, 13, 1, 8],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          iconClass: ['', '', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 20, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.at.hub.partner.assigned',
          steps: [0, 12, 13, 7, 8],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          iconClass: ['', '', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.at.hub.waiting.for.partner',
          steps: [0, 12, 13, 7, 8],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          iconClass: ['', '', '', 'el-icon-minus', ''],
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.partner.enroute.to.hub',
          steps: [0, 12, 13, 7, 8],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.partner.arrived.at.hub',
          steps: [0, 12, 13, 7, 8],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.partner.pickup.from.hub.confirmed.via.code',
          steps: [0, 12, 13, 7, 8],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.partner.enroute.to.buyer.location',
          steps: [0, 12, 13, 7, 8],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 7, 17],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.partner.arrived.at.buyer.location',
          steps: [0, 12, 13, 8, 9],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#324ba8', ''],
          icons: shallowRef([Check, Warning, Check, Minus, '']),
          showDriver: [false, false, false, true, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
          ],
          titles: [28, 27, 23, 12, 18],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.partner.submitted.items.to.buyer.confirmed.via.code',
          steps: [0, 12, 13, 7, 9],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', '#EE7D00', '#EE7D00'],
          icons: shallowRef([Check, Warning, Check, Check, Check]),
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'completed',
              status: true,
              format: 'ddd, MMM Do',
            },
          ],
          titles: [28, 27, 23, 7, 19],
          showReschedule: [false, false, false, false, false],
        },
        {
          event: 'event.delivery.order.canceled.by.seller',
          steps: [0, 10],
          colors: ['#EE7D00', '#EE7D00'],
          icons: shallowRef([Check, Check]),
          showDriver: [false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.order.canceled.by.sendy',
          steps: [0, 11],
          colors: ['#EE7D00', '#EE7D00'],
          icons: [Check, Check],
          showDriver: [false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
          ],
          titles: [28, 16],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.failed',
          steps: [0, 1, 7, 12, 9],
          colors: ['#EE7D00', '#EE7D00', '#EE7D00', '#9B101C', '#909399'],
          icons: shallowRef([Check, Check, Check, 'el-icon-remove', '']),
          showDriver: [false, false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            { status: false },
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
          ],
          titles: [28, 21, 8, 26, 18],
          showReschedule: [false, false, false, true, false],
        },
        {
          event: 'event.delivery.rescheduled.by.buyer',
          steps: [0, 12, 13, 9],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', ''],
          icons: shallowRef([Check, Warning, Check, '']),
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
          ],
          titles: [28, 27, 23, 18],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.rescheduled.by.seller',
          steps: [0, 12, 14, 9],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', ''],
          icons: shallowRef([Check, Warning, Check, '']),
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
          ],
          titles: [28, 27, 24, 18],
          showReschedule: [false, false, false, false],
        },
        {
          event: 'event.delivery.rescheduled.by.sendy',
          steps: [0, 12, 15, 9],
          colors: ['#EE7D00', '#9B101C', '#EE7D00', ''],
          icons: shallowRef([Check, Warning, Check, '']),
          showDriver: [false, false, false, false],
          dates: [
            {
              type: 'timeline',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
            {
              type: 'scheduled',
              status: true,
              format: 'ddd, MMM Do',
            },
            { status: false },
          ],
          titles: [28, 27, 25, 18],
          showReschedule: [false, false, false, false],
        },
      ],
    };
  },
  actions,
  getters,
  mutations,
});
